### PR TITLE
Data transformer beta dev

### PR DESCRIPTION
**Pull request by nisha20verma**

### CODE REVIEW

**Comment by dattranm** [comment]
@nisha20verma @sinuochen The reason why Unit test and Demo failed to run was because, in line 132 of association_evaluation.py, the input for cat_to_num_unsupervised is left unchanged, even though the required arguments of the function was changed:

Line 132 of association_evaluation.py,
`idf_encoded = cat_to_num_unsupervised(spark, idf_sample, list_of_cols=cat_cols, method_type=1)`

Change to the required arguments of cat_to_num_unsupervised function:
`def cat_to_num_unsupervised(idf, list_of_cols='all', drop_cols=[], method_type=1, index_order='frequencyDesc',
                            pre_existing_model=False, model_path="NA", output_mode='replace', print_impact=False)`

**Comment by dattranm** [comment]
@nisha20verma cat_to_num_unsupervised function changes on both main branch with Pull Request #42, and this Pull Request #43 created a conflict inside transformers.py. One-hot encoder changes and stat_unique changes in cat_to_num_unsupervised #42 are not reflected here. Can you take a look and resolve the conflict between 2 branches?

**Comment by dattranm** [comment]
For transformer.py functions:
Imputation_matrixFactorization output dataframe (odf) record order is messed up compare with the input record order. Consider keeping it in same order.

For datetime.py functions:
None of the functions are working properly there. All functions have the logic to return the original input if list_of_cols exists (in which, list_of_cols is a required argument, and it should always exist in order for the functions to run). Here is an example:
`def timestamp_to_unix (spark, idf, list_of_cols, precision="s", tz='local', output_mode="replace"):
    """
    :param spark: Spark Session
    :param idf: Input Dataframe
    :param list_of_cols: List of columns to transform e.g., ["col1","col2"].
                         Alternatively, columns can be specified in a string format,
                         where different column names are separated by pipe delimiter “|” e.g., "col1|col2".
    :param precision: "ms", "s".
                      "ms" option returns the number of milliseconds from the unix epoch (1970-01-01 00:00:00 UTC) .
                      "s" option returns the number of seconds from the unix epoch.
    :param tz: "local", "gmt", "utc".
               Timezone of the input column(s)
    :param output_mode: "replace", "append".
                        “replace” option replaces original columns with derived column. “append” option appends derived
                        column to the input dataset with a postfix "_unix" e.g. column X is appended as X_unix.
    :return: Output Dataframe with derived column
    """
    tz = tz.lower()
    list_of_cols = argument_checker('timestamp_to_unix', 
                                    {'list_of_cols': list_of_cols, 'all_columns': idf.columns,
                                     'output_mode': output_mode, 'precision': precision, 'tz': tz})
    if list_of_cols:
        return idf`

**Comment by dattranm** [comment]
> @nisha20verma cat_to_num_unsupervised function changes on both main branch with Pull Request #42, and this Pull Request #43 created a conflict inside transformers.py. One-hot encoder changes and stat_unique changes in cat_to_num_unsupervised #42 are not reflected here. Can you take a look and resolve the conflict between 2 branches?

@VishnuGowthem The conflict has been solved by Nisha. However, the changes to cat_to_num_unsupervised you made in #42 regarding one-hot encoding function optimization, cardinality_threshold default check are still not presented in this branch. Therefore, we cannot merge it for now. Can you guys have a discussion together and have a final push for cat_to_num_unsupervised function?

**Comment by VishnuGowthem** [comment]
> > @nisha20verma cat_to_num_unsupervised function changes on both main branch with Pull Request #42, and this Pull Request #43 created a conflict inside transformers.py. One-hot encoder changes and stat_unique changes in cat_to_num_unsupervised #42 are not reflected here. Can you take a look and resolve the conflict between 2 branches?
> 
> @VishnuGowthem The conflict has been solved by Nisha. However, the changes to cat_to_num_unsupervised you made in #42 regarding one-hot encoding function optimization, cardinality_threshold default check are still not presented in this branch. Therefore, we cannot merge it for now. Can you guys have a discussion together and have a final push for cat_to_num_unsupervised function?

this has been resolved with commit cb5dd7a. tests passed too.

**Comment by dattranm** [comment]
Datetime functions work properly like intended. Note that most of datetime functions receive column that has dtype as `datetime/datetime64,` but timestamp_to_string and dateformat_conversion functions return timestamp column that has dtype as `object`. Can consider changing the output of at least dateformat_conversion functions to datetime64 dtype timestamp, so that it will be ready to be used by other functions here.

**Comment by dattranm** [comment]
Functions works properly in Python 3.7 and Spark 2.4. The reason why unit tests and demo failing for other versions can be found in line 27, transformer.py
`from pyspark.ml.feature import Imputer, ImputerModel, StringIndexer, IndexToString, OneHotEncoderEstimator`
Need to remove at least `OneHotEncoderEstimator` from this line, as it already got imported dynamically based on Spark version:

`if version.parse(pyspark.__version__) < version.parse("3.0.0"):
    from pyspark.ml.feature import OneHotEncoderEstimator as OneHotEncoder
else:
    from pyspark.ml.feature import OneHotEncoder`

**Comment by dattranm** [comment]
After thorough testing, all the functions running as intended. Prior conflicts have been resolved, and it's ready to be merged now.

**Pull request merged**
