### PR TITLE
Refactor drift detection

### PR DESCRIPTION
**Pull request by ziedbouf**
refactoring drift detector and try to enhance argument validation and simplify the code if possible:
- [x] move distance to seperate file
- [x] move argument validation to seperate folder
- [x] check decorator for potential future use
- [x] fix example notebooks
- [x] fix docker build demo if needed

### CODE REVIEW

**Comment by ionicsolutions** [comment]
@ziedbouf Just FYI: If you'd like this to be included in the next release, this PR would have to be merged by Monday morning, otherwise it will have to wait for about a week (release is planned for the 25th at the latest)

No need to rush things, just wanted to let you know so that you're aware of the timeline

**Comment by ziedbouf** [comment]
Hi @ionicsolutions, i am on it just checking the design and will try to keep the refactor as much as light as possible to not break things, it should be ready before this week.

**Comment by ziedbouf** [comment]
@ionicsolutions  check this pull request, will keep test cases outside and they need to be careful written specially when i test the different test distribution distance measures.

**Comment by ionicsolutions** [comment]
@ziedbouf Thanks for all the work! The demo runs fail with `TypeError: _decorator() got an unexpected keyword argument 'list_of_cols'` Can you have a look, please?

**Comment by ziedbouf** [comment]
@ionicsolutions  fixed decorator validation, just have an issue with the [linter job](https://github.com/ziedbouf/anovos/runs/5217757151?check_suite_focus=true) as black works great locally but still raise an error with the space around the pow operator and locally everything is working fine locally and wasn't able to replicate the issue:
image
any suggestions?

**Comment by ionicsolutions** [comment]
@ziedbouf What version of `black` are you using? That's the only thing I can think of.

**Review by ionicsolutions — APPROVED** [review]

**Review by kajanansangar — APPROVED** [review]
thanks @ziedbouf & @ionicsolutions for reviewing

**Pull request merged**
