### PR TITLE
Publish notebook and Spark demo to Docker Hub upon release

### PR DESCRIPTION
**Pull request by ionicsolutions**

### CODE REVIEW

**Comment by ionicsolutions** [comment]
@kajanansangar We're still missing the credentials, of course, but could you please have a look if that's in line with your expectations?

We should discuss whether the demo should be provided for both Spark 2.x and 3.x as well

**Comment by ionicsolutions** [comment]
@kajanansangar @VishnuGowthem I believe we're ready for the merge. We'll need to test this with a pre-release at some point.

**Review by VishnuGowthem — APPROVED** [review]
I am good with the changes. 
Minor comment.. Readme could be maybe further modified later during release - like adding info on building images.
 ./examples/anovos_notebook/build_image.sh  
 or
 adding info about pulling version specific image from docker hub and running (as workflow ll build and upload multiple versions)

**Comment by ionicsolutions** [comment]
Yes, we're in a strange in-between-territory with this change. Once the images are on Docker Hub, we can further rewrite the README to fully reflect this situation.

**Comment by ionicsolutions** [comment]
As discussed in today's meeting

**Pull request merged**
